### PR TITLE
Add fresnel module

### PR DESCRIPTION
**Pull request by douglase**
An implementation of Fresnel diffraction propagation. See also issue #95.

### CODE REVIEW

**Comment by josePhoenix** [comment]
Thanks for this @douglase! I'll have a look through the code in the next week or two.

**Comment by josePhoenix** [comment]
I was reading through the code to try and wrap my head around it, and ran into something odd which I haven't been totally able to pin down.

There's a set of magic constants in fresnel.py:
```
# internal constants for types of plane
_PUPIL = 1
_IMAGE = 2
_DETECTOR = 3 # specialized type of image plane.
_ROTATION = 4 # not a real optic, just a coordinate transform
_INTERMED = 5
```

Which is different from the values in `poppy_core.py`:
```
# internal constants for types of plane
_PUPIL = 'PUPIL'
_IMAGE = 'IMAGE'
_DETECTOR = 'DETECTOR' # specialized type of image plane.
_ROTATION = 'ROTATION' # not a real optic, just a coordinate transform
```

I took a stab at normalizing this by making them the same in both, but found that the Hubble demo in the notebook looks totally different (like it's plotting the wrong plane) when _PUPIL in fresnel.py is changed from `1` to `'PUPIL'`. Any ideas?

**Comment by mperrin** [comment]
Those internal constants used to be ints originally, and I remember at some point one of us changed them to strings for slightly less inscrutability. Can't remember if I did that or you, @josePhoenix . I agree we need to have those consistent between poppy_core and fresnel...

**Comment by josePhoenix** [comment]
My gut feeling on normalizing the planetypes:

  * remove the underscores, so we're clear these are for "public use", after we...
  * ...change `is _PUPIL` type tests to `== _PUPIL`, so passing in the value or the variable reference has the same effect.

I'm slightly in favor of going back to integer valued magic constants, as well. (If we were Python 3.x only, we could use https://docs.python.org/3/library/enum.html, but alas.)

**Comment by mperrin** [comment]
The Py34 enum has been back ported (https://pypi.python.org/pypi/enum34) which admittedly would add another dependency for people on 2.7 but I'm OK with that. Yet another subtle factor to encourage people to upgrade to 3.4. :-)  I guess we should ask @cslocum first if adding a dependency on enum34 would be problematic for inclusion in Ureka though...

**Comment by mperrin** [comment]
Oh and yes you are 100% right about switching to `==` instead of `is` for this comparison. Good catch!

**Comment by josePhoenix** [comment]
Actually, if we use enums, the two are equivalent! I've got a branch that does that, but will clean it up a bit before PRing (and see if I can update the fresnel code to use it).

**Comment by josePhoenix** [comment]
@douglase It seems like something in the `fresnel.py` code is sensitive to whether `_PUPIL` is an integer or not, which I can't figure out. (It's also possible that the bug is elsewhere in POPPY and we never saw it before.)

Here's a comparison, running your `fresnel.py` code and the HST demo calculation before and after making a one-line change to import `_PUPIL` from `poppy_core`. The plot of the amplitude and phase at the focus show something weird going on.

https://gist.github.com/josePhoenix/462096e25fff10267a75

**Comment by douglase** [comment]
@josePhoenix,  greatings from SPIE.
 You definitely uncovered a bug. The planetype of the new analytic optical element, QuadPhase was hard coded as a pupil and that was overriding the user initialized 
intermediate planetype  of the secondary mirror.

Even though the planetype was wrong,  the example worked because fresnel.py used the old numerical planetype convention, and the check for if we were in a pupil plane was failing since the parent poppy. Wavefront class was initializing the planetype as u’PUPIL’, then when you fixed the planetype in fresnel propagate() thought it was in a pupil plane and dropped in the incident curvature.

I've fixed that, and made any Fresnel propagate wavefront intermediate unless the user specifies an optic is image or pupil.

This should fix the wavefront phase and amplitude when you use the poppy planetypes, but breaks display(), since the core plotting defaults to the image plane, the axes are no longer in meters. Not sure if we want to make display in poppy_core more general or just make a function that passes the wavefront to display as a pupil for plotting purposes?

**Comment by josePhoenix** [comment]
@mperrin and I were just digging into this. Thanks!

Oh, and I defer to him on how to change the `display()` stuff. It *sounds* like that brushes up against what he was just describing to me as a consequence of using angular units for image planes, which was a design decision he understands the ramifications of better than I do!

**Comment by mperrin** [comment]
Which display does it break, Wavefront.display() or OpticalElement.display?  

I haven't totally figured out the best overall API given that now there are two classes for regular-Wavefront and fresnel-Wavefront. (I sort of would like to rename the latter to FresnelWavefront in fact, to avoid having two different classes named Wavefront in the same package)

What I'd said before to @josePhoenix is somewhat related, which was that I wasn't sure if the Fresnel code would have trouble with IMAGE type optics, since those have dimensions in angular units. I was thinking of that in terms of propagation to optics and applying wavefront errors, not displays, but it's related of course.

**Comment by mperrin** [comment]
meanwhile, some github machinery coordination: @josePhoenix already merged a copy of this pull request in, but as a separate branch `poppy/fresnel` rather than into `poppy/master`. This will enable us to collaborate on further debugging, while still keeping it distinct from the main `poppy/master` until we all are happy that it's ready to go for public release. 

Since that branch exists (and I see that @josePhoenix and I both just nearly-simultaneously merged your latest commits into it, whoops :-), your code is now effectively merged in. 

I think at this point it would be the least confusing if we were to close this PR without merging it into master, and then we can just do further development with PRs against the fresnel branch from the three of us?  Is that a reasonable plan? 

Further comments to be posted on issue #95

**Comment by douglase** [comment]
Wavefront.display(), it didn't break it exactly, just labeled axes in arcseconds rather than meters. 

You are right about images planes being a problem, right now there is no handling of that case. 

Just got message regarding new branch, I can close this pull request.

**Pull request closed without merging**
