### PR TITLE
Notebook refresh + Python 3 syntax in notebooks

### PR DESCRIPTION
**Pull request by douglase**
Notebook refresh, python 3 print statements, poppy version reports and unit print fix.

running python 3.5.2.final.0 via a fresh Anaconda install on a MacBook Pro (Retina, 13-inch, Early 2015).

### CODE REVIEW

**Comment by mperrin** [comment]
Since notebook diffs don't show up in the viewer here, can you briefly summarize the changes? Was it just Python 3 syntax compatibility and other updates like that, or are there any more substantial edits that should be reviewed more closely?

**Comment by douglase** [comment]
1. I added poppy.__version__ to the top of each notebook at the bottom of the imports.
2. I changed print commands to print()
3.  I changed a few lines in MatrixFTCoronagraph_demo.ipynb to accommodate the new units on pupil_diam:

```
+    import astropy.units as u
-    "lamoD_asec = wavelen/fftcoron_annFPM_osys.planes[0].pupil_diam * 180/np.pi * 3600\n",
-    "print \"System diffraction resolution element scale (lambda/D) in arcsec: %.3f\" % lamoD_asec\n",
+    "lamoD_asec = (wavelen*u.m/fftcoron_annFPM_osys.planes[0].pupil_diam * u.radian).to(u.arcsec)\n",
+    "print(\"System diffraction resolution element scale (lambda/D)  \"+ str(np.round(lamoD_asec,4)))\n",
```

**Comment by josePhoenix** [comment]
Can I suggest some minor edits? This isn't anything to do with the changes you made, but if we're regenerating figures anyway...

In [POPPY Examples.ipynb](https://github.com/douglase/poppy/blob/22e600e4f4c66e9d24e63459615224871c5e4f37/notebooks/POPPY%20Examples.ipynb):

 * Change `%pylab inline` to `%pylab inline --no-import-all`
 * Add `plt.figure(figsize=(something, large))` to some of the cells that make figures with overlapping labels

**Comment by douglase** [comment]
(that last change shows that the notebooks aren't always using units consistently, but that might be for another day).

**Comment by douglase** [comment]
also added a smattering of plt.tight_layout()s.

**Comment by josePhoenix** [comment]
🎉

**Comment by josePhoenix** [comment]
The only Travis build that failed was the docs build, so I'm going to go ahead and merge this.

**Pull request merged**
