### PR TITLE
Implement PlaneType with an Enum

### PR DESCRIPTION
**Pull request by josePhoenix**
Introduces a dependency on the Python 3.4+ `enum` module, but the `enum34` backport is there as a dependency for older versions.

### CODE REVIEW

**Comment by mperrin** [comment]
Before I merge this, I would just like to hear from @cslocum confirmation that it's OK to add a dependency to the `enum34` package on py27, and have that added in as part of Ureka as well. I figure this is almost certainly acceptable given the inclusion of other packages like `six` and `unittest2` that are back ports and compatibility layers for 2.7 vs 3.4. Agreed?

**Comment by josePhoenix** [comment]
cc @jhunkeler since it sounds like you're currently working on packaging

**Comment by mperrin** [comment]
Paging @cslocum and @jhunkeler . It's been a week, if I don't hear any objections from either of you within the next day or two to adding the dependency on `enum34` to `poppy` , I'm going to go ahead and merge this.

**Comment by jhunkeler** [comment]
@josePhoenix pinged me via email. These github messages were going to my spam folder for some reason. Anyway, yes I'll add `enum24` to ssbdev tonight.

**Pull request merged**
